// Package persistence defines the control-plane and data-plane storage
// contracts of Plugfy: a thin, dialect-aware abstraction over the standard
// library's database/sql plus a namespaced key/value RegistryStore.
//
// database/sql is part of the Go standard library, so depending on it keeps the
// L1 baseplate a stdlib-only leaf; the decouple gate forbids only third-party
// imports. The concrete database *driver* (pgx, the SQLite driver) and the
// network wiring live in provider repos (spi.KindDatabase / spi.KindRegistry
// adapters) — never here. This package names the shapes the platform programs
// against; an adapter binds them to a real *sql.DB.
//
// Two planes share the abstraction:
//
//   - the data plane — [SQLDB] and the minimal [Rows]/[Row]/[Tx]/[Result]
//     interfaces — is the SQL surface multi-tenant services use, with dialect
//     awareness ([Dialect]) so a single query author targets both Postgres and
//     SQLite via [Rebind] and the fragment helpers.
//   - the control plane — [RegistryStore] — is the namespaced key/value store
//     the platform uses for its own registries (installed-module index, route
//     contributions, capability bindings).
package persistence

import (
	"context"
	"database/sql"
	"strings"
)

// ErrNoRows is returned by QueryRow-style lookups when no row matches. It is an
// alias of sql.ErrNoRows so callers can compare with errors.Is without
// importing database/sql directly.
var ErrNoRows = sql.ErrNoRows

// Dialect identifies the SQL dialect a [SQLDB] speaks. It drives [Rebind] and
// the fragment helpers so query authors write once and target both engines.
type Dialect string

const (
	// DialectPostgres is PostgreSQL: numbered placeholders ($1, $2),
	// jsonb, ON CONFLICT upserts.
	DialectPostgres Dialect = "postgres"
	// DialectSQLite is SQLite: positional placeholders (?), json1
	// extension, ON CONFLICT upserts.
	DialectSQLite Dialect = "sqlite"
)

// Result is the outcome of an Exec: the minimal subset of sql.Result the
// platform relies on.
type Result interface {
	// LastInsertId returns the integer generated by the database in
	// response to an insert, when the driver supports it.
	LastInsertId() (int64, error)
	// RowsAffected returns the number of rows affected by the statement.
	RowsAffected() (int64, error)
}

// Row is a single-row query result, scanned with Scan. It mirrors *sql.Row;
// Scan returns [ErrNoRows] when the query selected no rows.
type Row interface {
	Scan(dest ...any) error
}

// Rows is a multi-row query result. It mirrors the subset of *sql.Rows the
// platform uses: forward iteration with Next, per-row Scan, Close, and the
// deferred error via Err. Callers MUST Close the Rows.
type Rows interface {
	Next() bool
	Scan(dest ...any) error
	Close() error
	Err() error
	Columns() ([]string, error)
}

// Tx is an in-progress transaction. It carries the same Exec/Query/QueryRow
// surface as [SQLDB] plus Commit/Rollback. Statements run within the
// transaction until one of them is called.
type Tx interface {
	ExecContext(ctx context.Context, query string, args ...any) (Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) Row
	Commit() error
	Rollback() error
}

// SQLDB is the dialect-aware data-plane handle the platform programs against.
// It is the small surface of *sql.DB the services use, plus the two things the
// raw handle does not give: which [Dialect] it speaks, and a tenant-scoping
// hook ([WithTenant]) so multi-tenant adapters can pin a row-security tenant on
// the context before issuing statements.
type SQLDB interface {
	ExecContext(ctx context.Context, query string, args ...any) (Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) Row
	BeginTx(ctx context.Context, opts *sql.TxOptions) (Tx, error)

	// Dialect reports the SQL dialect this handle speaks so query authors
	// can select the right placeholder and fragment forms.
	Dialect() Dialect

	// WithTenant returns a context carrying the tenant scope. Tenant-aware
	// adapters read it to apply row-level security (e.g. SET LOCAL on
	// Postgres) for every statement issued with the returned context.
	WithTenant(ctx context.Context, tenant string) context.Context
}

// Rebind converts a query written with Postgres numbered placeholders ($1,
// $2, …) into the placeholder form the dialect expects. For
// [DialectPostgres] the query is returned unchanged; for [DialectSQLite] each
// $N is rewritten to a positional "?". Authors therefore write one query (the
// $N form) and Rebind targets either engine.
//
// Only top-level $N tokens are rewritten. A "$" not followed by a digit is left
// intact, and a doubled "$$" is treated as a literal single "$" (so Postgres
// dollar-quoted bodies and money literals survive).
func Rebind(d Dialect, query string) string {
	if d != DialectSQLite {
		return query
	}
	var b strings.Builder
	b.Grow(len(query))
	for i := 0; i < len(query); i++ {
		c := query[i]
		if c != '$' {
			b.WriteByte(c)
			continue
		}
		// "$$" -> literal "$".
		if i+1 < len(query) && query[i+1] == '$' {
			b.WriteByte('$')
			i++
			continue
		}
		// "$N" (one or more digits) -> "?". A lone "$" stays literal.
		j := i + 1
		for j < len(query) && query[j] >= '0' && query[j] <= '9' {
			j++
		}
		if j > i+1 {
			b.WriteByte('?')
			i = j - 1
			continue
		}
		b.WriteByte('$')
	}
	return b.String()
}

// Now returns the dialect's expression for the current UTC timestamp, suitable
// for inlining into a statement.
func Now(d Dialect) string {
	if d == DialectSQLite {
		return "CURRENT_TIMESTAMP"
	}
	return "now()"
}

// JSONExtract returns the dialect's expression extracting a top-level key from
// a JSON column. The key is the bare field name (no leading '$' or '.'); the
// caller is responsible for it being a trusted identifier, not user input.
func JSONExtract(d Dialect, column, key string) string {
	if d == DialectSQLite {
		// json_extract uses a JSONPath; key is a top-level field.
		return "json_extract(" + column + ", '$." + key + "')"
	}
	// Postgres ->> yields the value as text.
	return column + " ->> '" + key + "'"
}

// Upsert returns the dialect's conflict clause for an INSERT … that should
// update on a unique-key collision. conflictCols are the columns of the unique
// constraint; setAssignments are the "col = EXCLUDED.col" assignments applied
// on conflict. Both dialects support the same ON CONFLICT … DO UPDATE SET form,
// so the produced clause is identical — the helper exists so query authors do
// not hand-write it and so a future divergence has one place to live.
func Upsert(_ Dialect, conflictCols []string, setAssignments []string) string {
	return "ON CONFLICT (" + strings.Join(conflictCols, ", ") +
		") DO UPDATE SET " + strings.Join(setAssignments, ", ")
}
