// Package abi holds the golden Application Binary Interface (ABI) test for
// plugfy-common.
//
// plugfy-common is the L1 baseplate of the Plugfy polyrepo: every other unit
// pins "^1.x" of it, so an accidental breaking change to an exported signature
// in spi, events, errs, idempotency, ids, or resilience silently breaks the
// whole platform until each consumer fails to build downstream. This test
// freezes the exported public API surface into a committed golden file
// (testdata/api.golden) and fails when the surface drifts without an
// intentional golden update. A diff in this test at review time is the signal
// that a major-version-worthy break is being introduced.
//
// The snapshot is produced from the type-checked package, not from source text,
// so it is insensitive to comments, formatting and the internal order of
// declarations: only the externally observable contract (exported types, their
// underlying shapes, exported struct fields, interface method sets, exported
// functions, methods, constants and variables, and their fully-qualified types)
// is captured.
//
// To intentionally update the frozen surface after a reviewed, deliberate
// change, run:
//
//	go test ./abi -run TestGoldenABI -update
//
// and commit the regenerated testdata/api.golden alongside the change.
//
// This package is stdlib-only (go/ast, go/parser, go/types, go/importer); it
// adds no module dependency, preserving the L1 baseplate's decoupling gate.
package abi

import (
	"flag"
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// update, when set, rewrites testdata/api.golden from the current surface
// instead of comparing against it. It is the deliberate "I meant to change the
// ABI" switch.
var update = flag.Bool("update", false, "rewrite testdata/api.golden from the current public API surface")

// modulePath is the import path prefix of this module. Used to recognize
// intra-module imports (e.g. spi -> events) so they can be type-checked from
// local source rather than resolved as external dependencies.
const modulePath = "github.com/PlugfyOS/plugfy.framework.contracts"

// goldenPath is the committed snapshot of the frozen ABI.
const goldenPath = "testdata/api.golden"

// surfacePackages is the explicit, ordered list of packages whose exported
// surface is frozen. It is intentionally explicit (not discovered) so that
// adding a brand-new public package is itself a reviewed, deliberate act: a new
// package must be added here, which surfaces in review next to the new golden
// lines. Paths are relative to the module root (the parent of this test's
// directory).
var surfacePackages = []string{
	"api",
	"errs",
	"events",
	"idempotency",
	"ids",
	"installed",
	"resilience",
	"spi",
	"spi/core",
}

func TestGoldenABI(t *testing.T) {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		t.Fatalf("locate module root: %v", err)
	}

	loader := newLoader(moduleRoot)
	var b strings.Builder
	b.WriteString("# plugfy-common public ABI surface (golden snapshot)\n")
	b.WriteString("# Module: " + modulePath + "\n")
	b.WriteString("# Generated by abi.TestGoldenABI. Do not edit by hand.\n")
	b.WriteString("# Regenerate intentionally with: go test ./abi -run TestGoldenABI -update\n")

	for _, rel := range surfacePackages {
		pkg, err := loader.load(rel)
		if err != nil {
			t.Fatalf("type-check package %q: %v", rel, err)
		}
		b.WriteString("\n")
		b.WriteString(renderPackage(rel, pkg))
	}
	got := b.String()

	if *update {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("create testdata dir: %v", err)
		}
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated %s (%d bytes)", goldenPath, len(got))
		return
	}

	wantBytes, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden %s: %v (run `go test ./abi -run TestGoldenABI -update` to create it)", goldenPath, err)
	}
	want := string(wantBytes)

	if got != want {
		t.Errorf("public ABI surface drifted from %s.\n"+
			"If this change is intentional and major-version-worthy, review it carefully,\n"+
			"then regenerate the golden with:\n\n"+
			"    go test ./abi -run TestGoldenABI -update\n\n"+
			"and commit the updated golden alongside the change.\n\n%s",
			goldenPath, unifiedDiff(want, got))
	}
}

// ───────────────────────── source loader / type checker ─────────────────────

// loader type-checks the module's packages from local source. Intra-module
// imports are resolved against the on-disk source; everything else (the Go
// standard library) is delegated to the source-based importer, which keeps the
// whole test self-contained and free of prebuilt export data.
type loader struct {
	moduleRoot string
	fset       *token.FileSet
	std        types.Importer // fast: installed export data for the stdlib
	stdSource  types.Importer // fallback: type-checks the stdlib from source
	cache      map[string]*types.Package
	inProgress map[string]bool
}

func newLoader(moduleRoot string) *loader {
	fset := token.NewFileSet()
	return &loader{
		moduleRoot: moduleRoot,
		fset:       fset,
		// Default uses the toolchain's prebuilt export data for the standard
		// library — fast and deterministic for stdlib paths, which are the
		// only external paths this loader ever resolves (intra-module imports
		// are type-checked from source below).
		std: importer.Default(),
		// Source-based fallback for environments where export data is missing
		// (e.g. a stripped toolchain); keeps the test self-contained.
		stdSource:  importer.ForCompiler(fset, "source", nil),
		cache:      map[string]*types.Package{},
		inProgress: map[string]bool{},
	}
}

// load type-checks the module-relative package (e.g. "spi") and returns its
// *types.Package.
func (l *loader) load(rel string) (*types.Package, error) {
	importPath := modulePath + "/" + rel
	return l.importPackage(importPath)
}

// Import satisfies types.Importer for intra-module and stdlib dependencies.
func (l *loader) Import(path string) (*types.Package, error) {
	return l.importPackage(path)
}

func (l *loader) importPackage(importPath string) (*types.Package, error) {
	if pkg, ok := l.cache[importPath]; ok {
		return pkg, nil
	}
	if !strings.HasPrefix(importPath, modulePath) {
		// Delegate the standard library to the fast (export-data) importer,
		// falling back to source type-checking if export data is unavailable.
		pkg, err := l.std.Import(importPath)
		if err != nil {
			pkg, err = l.stdSource.Import(importPath)
			if err != nil {
				return nil, err
			}
		}
		l.cache[importPath] = pkg
		return pkg, nil
	}
	if l.inProgress[importPath] {
		return nil, fmt.Errorf("import cycle detected at %q", importPath)
	}
	l.inProgress[importPath] = true
	defer delete(l.inProgress, importPath)

	rel := strings.TrimPrefix(importPath, modulePath+"/")
	dir := filepath.Join(l.moduleRoot, filepath.FromSlash(rel))

	files, err := l.parseDir(dir)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no non-test Go files in %s", dir)
	}

	conf := types.Config{
		Importer: l, // recurse for nested intra-module imports
		// A non-nil Error makes type-checking continue past the first error so
		// the returned *types.Package is always fully populated; any genuine
		// failure still surfaces via the (error) return from Check.
		Error: func(error) {},
	}
	// info is not needed: only the package's exported scope is read.
	pkg, err := conf.Check(importPath, l.fset, files, nil)
	if err != nil {
		return nil, err
	}
	l.cache[importPath] = pkg
	return pkg, nil
}

// parseDir parses every non-test .go file in dir.
func (l *loader) parseDir(dir string) ([]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []*ast.File
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(l.fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}
	// Deterministic order is irrelevant for type-checking but keeps the
	// FileSet stable across runs.
	sort.Slice(files, func(i, j int) bool {
		return l.fset.Position(files[i].Pos()).Filename < l.fset.Position(files[j].Pos()).Filename
	})
	return files, nil
}

// ───────────────────────────── surface rendering ────────────────────────────

// qualifier renders package-qualified type names with the module-relative
// short path (e.g. "events.CloudEvent") and stdlib packages by their name
// (e.g. "context.Context"), so the golden is stable and human-readable.
func qualifier(this *types.Package) types.Qualifier {
	return func(other *types.Package) string {
		if other == this {
			return "" // same package: unqualified
		}
		p := other.Path()
		if strings.HasPrefix(p, modulePath+"/") {
			return strings.TrimPrefix(p, modulePath+"/")
		}
		return other.Name()
	}
}

// renderPackage emits the canonical, deterministic surface description of one
// package's exported scope.
func renderPackage(rel string, pkg *types.Package) string {
	q := qualifier(pkg)
	var lines []string

	scope := pkg.Scope()
	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj := scope.Lookup(name)
		switch o := obj.(type) {
		case *types.Const:
			// Capture the constant's value as well as its type: for typed
			// string/int constants (e.g. spi.KindModel = "model",
			// errs.CodeAuthTokenExpired = "auth.token_expired") the literal
			// value is part of the wire contract that consumers depend on, so
			// a value change is a breaking change that must surface here.
			lines = append(lines, fmt.Sprintf("const %s %s = %s", name, types.TypeString(o.Type(), q), o.Val().ExactString()))
		case *types.Var:
			lines = append(lines, fmt.Sprintf("var %s %s", name, types.TypeString(o.Type(), q)))
		case *types.Func:
			sig := o.Type().(*types.Signature)
			lines = append(lines, fmt.Sprintf("func %s%s", name, signatureString(sig, q)))
		case *types.TypeName:
			lines = append(lines, renderType(o, q)...)
		}
	}

	sort.Strings(lines)

	var b strings.Builder
	b.WriteString("package " + rel + " // " + pkg.Path() + "\n")
	for _, ln := range lines {
		b.WriteString("\t")
		b.WriteString(ln)
		b.WriteString("\n")
	}
	return b.String()
}

// renderType describes an exported named type: its declared kind, its exported
// structure (struct fields / interface methods), and its exported method set.
func renderType(tn *types.TypeName, q types.Qualifier) []string {
	name := tn.Name()
	named, _ := tn.Type().(*types.Named)
	underlying := tn.Type().Underlying()

	var lines []string

	switch u := underlying.(type) {
	case *types.Struct:
		lines = append(lines, fmt.Sprintf("type %s struct", name))
		for i := 0; i < u.NumFields(); i++ {
			f := u.Field(i)
			if !f.Exported() {
				continue
			}
			fieldDesc := fmt.Sprintf("type %s field %s %s", name, f.Name(), types.TypeString(f.Type(), q))
			if tag := u.Tag(i); tag != "" {
				fieldDesc += " `" + tag + "`"
			}
			if f.Embedded() {
				fieldDesc += " // embedded"
			}
			lines = append(lines, fieldDesc)
		}
	case *types.Interface:
		lines = append(lines, fmt.Sprintf("type %s interface", name))
		var methods []string
		for i := 0; i < u.NumMethods(); i++ {
			m := u.Method(i)
			if !m.Exported() {
				continue
			}
			sig := m.Type().(*types.Signature)
			methods = append(methods, fmt.Sprintf("type %s method %s%s", name, m.Name(), signatureString(sig, q)))
		}
		// Embedded interfaces contribute their methods to the method set; the
		// explicit-method loop above already enumerates the full set for
		// interfaces, but we also record embedded interface names so a change
		// in composition is visible even when the method set is unchanged.
		for i := 0; i < u.NumEmbeddeds(); i++ {
			methods = append(methods, fmt.Sprintf("type %s embeds %s", name, types.TypeString(u.EmbeddedType(i), q)))
		}
		sort.Strings(methods)
		lines = append(lines, methods...)
	default:
		// Defined type over a non-struct/non-interface underlying type
		// (e.g. `type Kind string`, `type State int`).
		lines = append(lines, fmt.Sprintf("type %s %s", name, types.TypeString(underlying, q)))
	}

	// Exported methods declared on the named type (pointer and value
	// receivers). Interface method sets are handled above; for defined
	// concrete types this captures the behavioral surface.
	if named != nil {
		var methods []string
		for i := 0; i < named.NumMethods(); i++ {
			m := named.Method(i)
			if !m.Exported() {
				continue
			}
			sig := m.Type().(*types.Signature)
			recv := "(T)"
			if _, isPtr := sig.Recv().Type().(*types.Pointer); isPtr {
				recv = "(*T)"
			}
			methods = append(methods, fmt.Sprintf("type %s method %s %s%s", name, recv, m.Name(), signatureString(sig, q)))
		}
		sort.Strings(methods)
		lines = append(lines, methods...)
	}

	return lines
}

// signatureString renders a function/method signature without the receiver,
// using the supplied qualifier. Parameter names are deliberately omitted: they
// are not part of the ABI; only the ordered parameter and result types and the
// variadic flag matter.
func signatureString(sig *types.Signature, q types.Qualifier) string {
	var b strings.Builder
	b.WriteString("(")
	params := sig.Params()
	for i := 0; i < params.Len(); i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		t := params.At(i).Type()
		if sig.Variadic() && i == params.Len()-1 {
			// Render the variadic parameter as ...elem.
			if sl, ok := t.(*types.Slice); ok {
				b.WriteString("...")
				b.WriteString(types.TypeString(sl.Elem(), q))
				continue
			}
		}
		b.WriteString(types.TypeString(t, q))
	}
	b.WriteString(")")

	results := sig.Results()
	switch results.Len() {
	case 0:
		// no results
	case 1:
		b.WriteString(" ")
		b.WriteString(types.TypeString(results.At(0).Type(), q))
	default:
		b.WriteString(" (")
		for i := 0; i < results.Len(); i++ {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(types.TypeString(results.At(i).Type(), q))
		}
		b.WriteString(")")
	}
	return b.String()
}

// ──────────────────────────────── helpers ──────────────────────────────────

// findModuleRoot walks up from the working directory to the directory holding
// go.mod, so the test works regardless of the directory `go test` runs it from.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s upward", dir)
		}
		dir = parent
	}
}

// unifiedDiff renders a minimal line-oriented diff (added/removed lines) to make
// surface drift legible in test output without pulling in an external diff
// library. It compares the two line multisets: a line present more often in
// want than in got is reported as removed (-), and vice versa as added (+). It
// is a presentation aid only; the equality decision is the exact string compare
// in the test body.
func unifiedDiff(want, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")

	wantCount := map[string]int{}
	for _, l := range wantLines {
		wantCount[l]++
	}
	gotCount := map[string]int{}
	for _, l := range gotLines {
		gotCount[l]++
	}

	var removed []string
	for _, l := range wantLines {
		if wantCount[l] > gotCount[l] {
			removed = append(removed, l)
			wantCount[l]-- // count each surplus occurrence once
		}
	}
	var added []string
	for _, l := range gotLines {
		if gotCount[l] > wantCount[l] {
			added = append(added, l)
			gotCount[l]--
		}
	}

	var b strings.Builder
	b.WriteString("--- want (golden)\n+++ got (current)\n")
	for _, l := range removed {
		b.WriteString("- " + l + "\n")
	}
	for _, l := range added {
		b.WriteString("+ " + l + "\n")
	}
	if len(removed) == 0 && len(added) == 0 {
		b.WriteString("(line multiset identical; the difference is line order — re-run with -update if intentional)\n")
	}
	return b.String()
}
